/// <reference lib="webworker" />
import { PrecacheController, PrecacheRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { NavigationRoute, Router } from 'workbox-routing';
import { ACTIVATE_BUILD_MESSAGE, BUILD_ID_MESSAGE, COMPLETE_OFFLINE_MESSAGE, USE_NETWORK_MESSAGE } from '../src/logic/pwa/protocol';
import { installStreamDownloadWorker } from '../src/utils/download/service-worker';

import { createOfflineHandoff } from './offline-handoff';
import { waitForActiveCleanup } from './precache-lifecycle';

declare const __PWA_BUILD_ID__: string;
declare const self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: Array<{ url: string; revision: string | null }>;
};

// Register before BOTH the precache router and network-only update path. Local
// generated bytes must never become a server request, even during an update.
const downloads = installStreamDownloadWorker({
  scope: self,
  canPrepare: () => !handoff.isDraining(),
  onIdle: () => handoff.resume(),
});
const handoff = createOfflineHandoff({ registration: self.registration, isIdle: downloads.isIdle });

// One opt-in record per application scope, NOT per tab/resource. Its value is
// THIS worker's build ID. A replacement worker starts cache-first, even after a
// browser restart. No page can restore an obsolete worker to cache-first mode.
const scope = new URL(self.registration.scope);
const modeCache = `naidan-pwa-network-mode:${scope.href}`;
const modeKey = new URL('__network_mode__', scope).href;
let networkOnly = caches.open(modeCache).then(async cache =>
  (await (await cache.match(modeKey))?.text()) === __PWA_BUILD_ID__).catch(error => {
  // An unreadable opt-in must not serve stale HTML as a successful update, but
  // must not block the online application either. There is no cache fallback.
  console.error('[PWA] Failed to read network update mode; using the network.', error);
  return true;
});

const precache = new PrecacheController({
  plugins: [{
    async handlerDidError({ request, error, event }) {
      if (event.type === 'install') console.error('[PWA] Failed to precache an application resource.', request.url, error);
      // Report the ORIGINAL error; never turn an incomplete install into success.
      return undefined;
    },
  }],
});
// Full, automatically generated manifest: no minimum-files list or partial install.
precache.addToCacheList(self.__WB_MANIFEST);
self.addEventListener('install', event => {
  event.waitUntil((async () => {
    await waitForActiveCleanup({ registration: self.registration });
    await precache.install(event);
  })());
});
self.addEventListener('activate', event => {
  // If C is already writing, B must not delete C's entries. If C starts after
  // this check, its install waits for this activation before writing anything.
  // A later uncontended activation cleans up any entries left by a failed C.
  if (!self.registration.installing) event.waitUntil(precache.activate(event));
});
cleanupOutdatedCaches();
const router = new Router();
router.registerRoute(new PrecacheRoute(precache));
router.registerRoute(new NavigationRoute(precache.createHandlerBoundToURL('index.html')));

self.addEventListener('fetch', event => {
  const url = new URL(event.request.url);
  // Leave other origins, scopes and methods to the browser. In particular,
  // this worker does not wrap model/API requests or their response streams.
  if (event.request.method !== 'GET' || url.origin !== scope.origin || !url.pathname.startsWith(scope.pathname)) return;
  const response = (async () => {
    // The deliberate tradeoff is SCOPE-wide: all tabs/workers still controlled
    // by this generation use the network. This avoids guessing worker ancestry,
    // mixing old fixed-name runtime files, or changing any model/user cache.
    if (await networkOnly) return fetch(event.request, { cache: 'no-store' });
    return router.handleRequest({ request: event.request, event }) ?? fetch(event.request);
  })();
  event.respondWith(response);
  event.waitUntil(response.then(() => undefined, () => undefined));
});

self.addEventListener('message', event => {
  const source = event.source;
  const fromActive = source !== null && source === self.registration.active;
  const fromPage = event.origin === scope.origin && source && 'url' in source && 'type' in source
    && source.type === 'window' && source.url.startsWith(scope.href);
  if (!fromPage && !fromActive) return;
  const data: unknown = event.data;
  if (!data || typeof data !== 'object' || !('type' in data)) return;
  if (data.type === ACTIVATE_BUILD_MESSAGE) {
    // Only the active worker can prove ALL its streams have drained. The build
    // check prevents a replaced waiting B from accidentally activating C.
    if (fromActive && 'buildId' in data && data.buildId === __PWA_BUILD_ID__) event.waitUntil(self.skipWaiting());
    return;
  }
  if (data.type === 'SKIP_WAITING') {
    if (fromPage) event.waitUntil(self.skipWaiting());
    return;
  }
  const reply = event.ports[0];
  if (!reply) return;
  if (data.type === BUILD_ID_MESSAGE) {
    // eslint-disable-next-line local-rules-worker-transport/no-unchecked-worker-transport -- Read-only, versioned, validated one-shot identity; available even during install.
    reply.postMessage({ type: BUILD_ID_MESSAGE, buildId: __PWA_BUILD_ID__ });
    reply.close();
    return;
  }
  if (!fromPage) {
    reply.close(); return;
  }
  if (data.type === COMPLETE_OFFLINE_MESSAGE) {
    event.waitUntil((async () => {
      let accepted = false;
      try {
        // matchAll without includeUncontrolled enumerates THIS worker's clients.
        // Do not rely on ServiceWorkerGlobalScope.serviceWorker (not universal),
        // or let an installer with an empty session map act for the active worker.
        const active = self.registration.active;
        const controlled = await self.clients.matchAll({ type: 'window' });
        if (active === self.registration.active && source && 'id' in source && controlled.some(client => client.id === source.id)
          && 'buildId' in data && typeof data.buildId === 'string' && data.buildId.trim()) accepted = await handoff.request({ buildId: data.buildId });
      } catch (error) {
        console.warn('[PWA] Offline handoff could not be prepared.', error);
      }
      // eslint-disable-next-line local-rules-worker-transport/no-unchecked-worker-transport -- Literal acknowledgement of an armed worker-owned handoff, not activation completion.
      reply.postMessage(accepted ? COMPLETE_OFFLINE_MESSAGE : false);
      reply.close();
    })());
    return;
  }
  // Unrecognized messages/ports may belong to the local download protocol.
  if (data.type !== USE_NETWORK_MESSAGE) return;
  event.waitUntil((async () => {
    try {
      // Persist BEFORE acknowledging, so a reload/worker restart cannot return
      // to old caches. Installation uses native fetch and is unaffected.
      await (await caches.open(modeCache)).put(modeKey, new Response(__PWA_BUILD_ID__));
      networkOnly = Promise.resolve(true);
      // eslint-disable-next-line local-rules-worker-transport/no-unchecked-worker-transport -- One scoped command with a literal acknowledgement, not a long-lived worker API.
      reply.postMessage(USE_NETWORK_MESSAGE);
    } catch (error) {
      console.error('[PWA] Failed to enable network updating.', error);
      // eslint-disable-next-line local-rules-worker-transport/no-unchecked-worker-transport -- Failure acknowledgement lets the page stay usable and offer a retry.
      reply.postMessage(false);
    } finally {
      reply.close();
    }
  })());
});
