version: 2
project_name: naidan-server
builds:
  - env:
      - CGO_ENABLED=0
    dir: ./naidan-server
    main: .
    hooks:
      before:
        - go run build.go
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
      - 386
      - ppc64le
      - s390x
      - mips64
      - mips64le
    goarm:
      - 6
      - 7
    main: ./naidan-server/main.go
archives:
  - name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}-{{ .Mips }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
nfpms:
  - license: MIT
    maintainer: Ryo Ota <nwtgck@nwtgck.org>
    homepage: https://github.com/nwtgck/naidan
    formats:
      - rpm
      - deb
    file_name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}-{{ .Mips }}{{ end }}'
checksum:
  name_template: 'checksums.txt'
release:
  github:
  disable: false
  prerelease: auto
  name_template: "v{{.Version}}"
  extra_files:
    - glob: ./dist/naidan-standalone-*.zip
    - glob: ./dist/naidan-hosted-*.zip
